cookie:
  expiry_days: 30
  key: assinatura_secreta_SPM_criado_por_Ismael_adoro_pizza_la_li_lu_le_lo
  name: cookie_sistema
credentials:
  usernames:
    carol_adm:
      email: adm@mumix.com.br
      first_name: Carol
      last_name: adm
      logged_in: false
      password: $2b$12$UCjpHYm7ekUDnphx5mxYhOHd27jYHintWxhDLBeGNaFS2jkFiWSE2
      roles: usuario
    ijunior:
      email: analista.adm@mumix.com.br
      failed_login_attempts: 0
      logged_in: true
      name: Ismael Junior
      password: $2b$12$JcEhH4Pt7rXUEeLc5flGa.7CBFQggGzLkEz60HYVFRxA1hUESWUsG
      roles: cliente
    sabrina_adm:
      email: administrativo@mumix.com.br
      first_name: Sabrina
      last_name: adm
      logged_in: false
      password: $2b$12$RRc4fJxAe6ejCcdpJiIE8ODtbAJSHzZARoEPOI/2ZbqW3crRn2fYi
      roles: administrador
    usuario_teste:
      email: teste@gmail.com
      first_name: NomeFulano
      last_name: NomeCiclano
      logged_in: false
      password: $2b$12$Dk7QHq.7fCbBRqqvpAl6aO97kbuTf/7Q72O7tRiUcG2z.dTVQrzZK
      roles: cliente
